# 60-prompt.zsh - Powerlevel10k prompt, standalone (no Oh My Zsh).
# The instant-prompt block lives at the top of .zshrc (it must run before any
# output); this loads the theme itself + your generated styling. Runs after
# 50-completion so p10k sees the finished completion system.

# Homebrew's p10k. (If you ever install it by git clone instead, add that path.)
if [[ -n "$HOMEBREW_PREFIX" && -r "$HOMEBREW_PREFIX/share/powerlevel10k/powerlevel10k.zsh-theme" ]]; then
  source "$HOMEBREW_PREFIX/share/powerlevel10k/powerlevel10k.zsh-theme"
fi

# Prompt styling generated by `p10k configure`. Kept IN the repo and symlinked to
# ~/.p10k.zsh by install.sh, so `p10k configure` (which writes ~/.p10k.zsh) edits
# the tracked copy. Sourced from the repo path so it also works before install.
[[ -r "$ZSH_CONFIG_DIR/.p10k.zsh" ]] && source "$ZSH_CONFIG_DIR/.p10k.zsh"
